"use strict";

var getId = function (value) {
    return document.getElementById(value);
};

(function () {
    let html = getId('html');
    let css = getId('css');
    let js = getId('js');
    let code = getId('code');

    // contentWindow property returns Window object generated by an iframe element
    let frame = code.contentWindow.document;

    try {
        document.body.onkeyup = function () {
            frame.open();
            frame.writeln(html.value + "<style>" + css.value + "</style>" + "<script>" + js.value + "</script>");
            frame.close();
        };
    } catch (e) {
        console.log('Error: ' + e);
    }
})();
